/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Logic.*;
import java.util.ArrayList;

/**
 *
 * @author cbust
 */
public class ShowPersonalData extends javax.swing.JPanel {

    /**
     * Creates new form ShowPersonalData
     */
    public ShowPersonalData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        textName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textBirdth = new javax.swing.JTextField();
        textHeigth = new javax.swing.JTextField();
        textWidth = new javax.swing.JTextField();
        textGender = new javax.swing.JTextField();
        textID = new javax.swing.JTextField();
        textAnalysis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("LAST ANALYSIS");
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 110, 40));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("ID");
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 40));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setText("NAME");
        add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, 40));

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField6.setText("LAST NAME");
        add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 40));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField7.setText("BIRTH DATE");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 40));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField8.setText("HEIGHT");
        add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, 40));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("WEIGTH");
        add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 110, 40));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField10.setText("GENDER");
        add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 110, 40));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setLayout(null);

        textName.setEditable(false);
        textName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textName);
        textName.setBounds(0, 61, 260, 40);

        textLastName.setEditable(false);
        textLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textLastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textLastName);
        textLastName.setBounds(0, 120, 260, 40);

        textBirdth.setEditable(false);
        textBirdth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textBirdth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textBirdth);
        textBirdth.setBounds(0, 180, 260, 40);

        textHeigth.setEditable(false);
        textHeigth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textHeigth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textHeigth);
        textHeigth.setBounds(0, 240, 260, 40);

        textWidth.setEditable(false);
        textWidth.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textWidth.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textWidth);
        textWidth.setBounds(0, 300, 260, 40);

        textGender.setEditable(false);
        textGender.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textGender.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textGenderActionPerformed(evt);
            }
        });
        jPanel1.add(textGender);
        textGender.setBounds(0, 360, 260, 40);

        textID.setEditable(false);
        textID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textIDActionPerformed(evt);
            }
        });
        jPanel1.add(textID);
        textID.setBounds(0, 0, 260, 40);

        textAnalysis.setEditable(false);
        textAnalysis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textAnalysis.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(textAnalysis);
        textAnalysis.setBounds(0, 420, 260, 40);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 260, 460));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/ferynando7/NetBeansProjects/Baropodometro/src/images/foot.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 480, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void textGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textGenderActionPerformed

    private void textIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    public javax.swing.JTextField textAnalysis;
    public javax.swing.JTextField textBirdth;
    public javax.swing.JTextField textGender;
    public javax.swing.JTextField textHeigth;
    public javax.swing.JTextField textID;
    public javax.swing.JTextField textLastName;
    public javax.swing.JTextField textName;
    public javax.swing.JTextField textWidth;
    // End of variables declaration//GEN-END:variables
}
